In [14]:
from typing import Callable
import numpy as np

In the next function, we implement the Romberg algorithm. We create an array with size (n,m) which we will fill using the following method.

We first calculate R(0,0) using the formula, $$R(0,0) = \frac{1}{2}  (b-a)  [f(a) + f(b)]$$

We then calculate R(n,0) using the formula,
$$R(n,0) = \frac{1}{2}  R(n-1,0) + h  \sum_{k=1}^{2^{n-1}}f[a + (2k - 1)h]$$
where $n ≥ 1$ and $h = \frac{b-a}{2^n}$.

Finally we calculate R(n,m) using the formula,
$$R(n,m) = R(n,m-1) + \frac{1}{4^m - 1}  [R(n,m-1) - R(n - 1, m - 1)]$$

For $n ≥ 1$ and $m ≥ 1$

All these values are stored in the matrix we created in the beginning.

In [15]:
def rmbrg(
    function: Callable[[float], float],
    left_boundry: float = None,
    right_boundry: float = None,
    n: int = None,
    m: int = None,
):
    left_boundry = (
        left_boundry
        if left_boundry is not None
        else int(input("enter left boundry: "))
    )
    right_boundry = (
        left_boundry
        if right_boundry is not None
        else int(input("enter right boundry: "))
    )
    n = n if n is not None else int(input("enter n: "))
    m = m if m is not None else int(input("enter m: "))

    matrix = np.zeros((n, m), dtype=np.longdouble)
    matrix[0][0] = (
        0.5
        * (right_boundry - left_boundry)
        * (function(left_boundry) + function(right_boundry))
    )

    for i in range(n):
        if i != 0:
            sum = 0
            for j in range((2 ** (i - 1))):
                sum += function(
                    left_boundry
                    + ((2 * (j + 1)) - 1)
                    * ((right_boundry - left_boundry) / (2 ** i))
                )
            matrix[i][0] = (0.5 * matrix[i - 1][0]) + (
                (((right_boundry - left_boundry) / (2 ** i))) * sum
            )

        for j in range(min(m, i + 1)):
            if i != 0 and j != 0:
                matrix[i][j] = matrix[i][j - 1] + (1 / ((4 ** j) - 1)) * (
                    matrix[i][j - 1] - matrix[i - 1][j - 1]
                )

    return matrix

In [16]:
def main():
    print(rmbrg((lambda x: 4 / (1 + (x ** 2))), 0, 1, 3, 3))

In [17]:
if __name__ == "__main__":
    main()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
